# Generated by Django 5.0.2 on 2024-04-05 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_sideimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sideimages',
            name='height',
        ),
        migrations.RemoveField(
            model_name='sideimages',
            name='width',
        ),
        migrations.AddField(
            model_name='sideimages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideimages',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sideimages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sideimages',
            name='image',
            field=models.ImageField(upload_to='side_images/', verbose_name='Image'),
        ),
    ]
